FROM php:8.1-fpm

RUN apt-get update && apt-get -y install curl libpq-dev
RUN apt-get update && apt-get install -y \
    build-essential\
    libfreetype6-dev\
    locales\
    jpegoptim optipng pngquant gifsicle\
    vim\
    unzip\
    libonig-dev\
    libjpeg62-turbo-dev\
    libpng-dev\
    libzip-dev\
    zip\
    ca-certificates\
    && docker-php-ext-configure gd --with-freetype --with-jpeg\
    && docker-php-ext-install -j$(nproc) gd\
    && docker-php-ext-install zip

RUN docker-php-ext-install pdo pdo_pgsql pgsql opcache

RUN docker-php-ext-install mbstring mysqli pdo_mysql exif pcntl bcmath\
    && docker-php-ext-configure gd --with-freetype --with-jpeg

RUN curl -sS https://getcomposer.org/installer | php -- --intall-dir-/usr/local/bin --filename=composer

ARG NODE_VERSION=16.17.1
ARG NODE_PACKAGE=node-v$NODE_VERSION-linux-x64
ARG NODE_HOME=/opt/$NODE_PACKAGE

ENV NODE_PATH $NODE_HOME/lib/node_modules
ENV PATH $NODE_HOME/bin:$PATH

RUN curl https://nodejs.org/dist/v$NODE_VERSION/$NODE_PACKAGE.tar.gz | tar -xzC /opt/