version: '3'
services:
  postgresql:
    image: postgres:15.1-alpine
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=users
    networks:
      - db
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgadmin
    ports:
      - 91:80
    environment:
      - PGADMIN_HOST=postgresql
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - ./db_backup:/var/lib/pgadmin/storage/ 
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  pg_data:
  db_backup: